version: 0.2

phases:
  build:
    commands:
      - echo direct commit main
      - echo direct commit main 2
      - echo direct commit main 3
      - ls
      - whoami
      - ls .git
      - cat .git/FETCH_HEAD
